name: Test-Build
on:
  push:
    branches:
      - main
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Install Node on the runner
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: "20.x" # Updated to Node.js 20.x as recommended

      # Make directory to upload the test results
      - name: Make Directory for results
        run: mkdir -p testResults

      # Install the newman command line utility and also install the html extra reporter
      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      # Run the POSTMAN collection
      - name: Run POSTMAN collection
        run: |
        #   newman run petstore.collection.json -r json --reporter-htmlextra-export --reporter-htmlextra-darkTheme
        
      # To List the Content
      - name: List Test Results
        run: ls -la testResults

      # Upload the contents of Test Results directory to workspace
      - name: Output the run Details
        uses: actions/upload-artifact@v4
        with:
          name: RunReports
          path: testResults
          
      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_branch: gh-pages
            publish_dir: testResults/htmlreport.html
permissions:
  contents: write